// Test generated by RoostGPT for test petstore-java using AI Type Open AI and AI Model gpt-4

package hello.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;

class Pet_Pet_41e572ac4b_Test {

    private Pet pet;

    @BeforeEach
    void setUp() {
        pet = Mockito.mock(Pet.class);
    }

    @Test
    void testPetNameSuccess() {
        String name = "Rex";
        Mockito.when(pet.getName()).thenReturn(name);
        Pet testPet = new Pet(name);
        assertEquals(name, testPet.getName());
    }

    @Test
    void testPetNameFailure() {
        String name = "Rex";
        Mockito.when(pet.getName()).thenReturn("Max");
        Pet testPet = new Pet(name);
        assertNotEquals("Max", testPet.getName());
    }

    @Test
    void testPetNameNull() {
        String name = null;
        Mockito.when(pet.getName()).thenReturn(name);
        Pet testPet = new Pet(name);
        assertNull(testPet.getName());
    }
}
