// Test generated by RoostGPT for test petstore-java using AI Type Open AI and AI Model gpt-4

package hello.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class Pet_getId_3d7d4d4e1a_Test {

    @InjectMocks
    private Pet pet;

    @BeforeEach
    public void setUp() {
        pet.setId(100L);
    }

    @Test
    public void testGetId_Success() {
        long expectedId = 100L;
        long actualId = pet.getId();
        assertEquals(expectedId, actualId, "The expected ID does not match the actual ID");
    }

    @Test
    public void testGetId_Failure() {
        long unexpectedId = 101L;
        long actualId = pet.getId();
        assertEquals(unexpectedId, actualId, "The unexpected ID should not match the actual ID");
    }
}
