// Test generated by RoostGPT for test petstore-java using AI Type Open AI and AI Model gpt-4

package hello.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class PetTest {

    @Test
    public void testPetConstructor() {
        Pet pet = new Pet();
        Assertions.assertNotNull(pet);
    }

    @Test
    public void testPetId() {
        Pet pet = new Pet();
        Long expectedId = 1L;
        pet.setId(expectedId);
        Assertions.assertEquals(expectedId, pet.getId());
    }

    @Test
    public void testPetName() {
        Pet pet = new Pet();
        String expectedName = "Test Pet";
        pet.setName(expectedName);
        Assertions.assertEquals(expectedName, pet.getName());
    }
}
