// Test generated by RoostGPT for test petstore-java using AI Type Open AI and AI Model gpt-4

package hello.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Pet_getName_8400ac6fb7_Test {

    @Mock
    private Pet pet;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetName_Success() {
        String expectedName = "Fluffy";
        when(pet.getName()).thenReturn(expectedName);

        String actualName = pet.getName();

        assertEquals(expectedName, actualName, "Pet name should be Fluffy");
    }

    @Test
    public void testGetName_Failure() {
        String unexpectedName = "Bobby";
        when(pet.getName()).thenReturn("Fluffy");

        String actualName = pet.getName();

        assertNotEquals(unexpectedName, actualName, "Pet name should not be Bobby");
    }
}
